apiVersion: v1
kind: PersistentVolume
metadata:
  name: vprodb-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/vprodb"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
